# Numpy


In [ ]:
import numpy as np

In [ ]:
a = np.array([1,2,3,4,5]) # 1st array -> vector
a

array([1, 2, 3, 4, 5])

In [ ]:
type(a)

numpy.ndarray

In [ ]:
a.shape # -> tek boyutlu 5 elemandan oluşan bir array

(5,)

In [ ]:
a.ndim # -> n dimension - kaç boyutlu gösterir

1

In [ ]:
a

array([1, 2, 3, 4, 5])

In [ ]:
print(f"""
a[0]: {a[0]}
a[1]: {a[1]}
a[2]: {a[2]}
""")


a[0]: 1
a[1]: 2
a[2]: 3



In [ ]:
b = [1,2,3,4,5,6]
b[0] = 11
b

[11, 2, 3, 4, 5, 6]

In [ ]:
b = np.array([11, 22, 33, 44, 55])
b[0] = 1111111
b

array([1111111,      22,      33,      44,      55])

In [ ]:
b[1] = 11.222
b

array([1111111,      11,      33,      44,      55])

In [ ]:
c = np.array([[1,2,3,4,5],
              [6,7,8,9,10]
              ])

2 boyutlu dizi oluşturduk

In [ ]:
c

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
c.shape

(2, 5)

In [ ]:
c.ndim

2

In [ ]:
d = np.array([[[[1,2,3,4,5],
              [6,7,8,9,10],
              [11,22,33,44,55]
              ]]])
d.ndim

4

# Special Methods

In [ ]:
s = np.zeros((3,2))
s

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
s = np.zeros((3,2)).astype("int64")
print(s)

[[0 0]
 [0 0]
 [0 0]]


In [ ]:
s2 = np.ones((2, 3)).astype("int64")
s2

array([[1, 1, 1],
       [1, 1, 1]])

In [ ]:
s3 = np.full((3,3), 8)
s3

array([[8, 8, 8],
       [8, 8, 8],
       [8, 8, 8]])

In [ ]:
s4 = np.empty((4,5))
s4

array([[0. , 0. , 0.3, 1. , 0. ],
       [0. , 1. , 1. , 1. , 1. ],
       [1. , 1. , 1. , 0. , 0. ],
       [1. , 0.5, 0. , 0. , 1. ]])

random verilerle oluşturduk

In [ ]:
s5 = np.eye(4)
s5

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

diyagonal matris yaptık. köşegen değerlerini 1 yaptık

In [ ]:
s8 = np.arange(0,10,1)
s8 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

0-10 arası 1 boyutlu dizi oluşturduk

In [ ]:
s9 = np.linspace(2,3,5)
s9

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [ ]:
s10 = np.random.randint(5,10, size=(5,5))
s10

array([[6, 5, 7, 7, 5],
       [9, 9, 9, 7, 7],
       [7, 5, 9, 7, 9],
       [7, 9, 7, 8, 8],
       [5, 9, 6, 8, 5]])

In [ ]:
s10[1,1]

9

In [ ]:
s11 = np.random.randint(5,10, size=(5,4))
s11

array([[5, 9, 7, 5],
       [8, 8, 8, 6],
       [5, 5, 8, 8],
       [7, 5, 7, 5],
       [7, 8, 8, 5]])

In [ ]:
s11.reshape(10,2)

array([[5, 9],
       [7, 5],
       [8, 8],
       [8, 6],
       [5, 5],
       [8, 8],
       [7, 5],
       [7, 5],
       [7, 8],
       [8, 5]])

In [ ]:
s11.reshape(4,5)

array([[5, 9, 7, 5, 8],
       [8, 8, 6, 5, 5],
       [8, 8, 7, 5, 7],
       [5, 7, 8, 8, 5]])

In [39]:
#ravel
s11.ravel()

array([5, 9, 7, 5, 8, 8, 8, 6, 5, 5, 8, 8, 7, 5, 7, 5, 7, 8, 8, 5])

In [42]:
s11 = s11.ravel()
s11

array([5, 9, 7, 5, 8, 8, 8, 6, 5, 5, 8, 8, 7, 5, 7, 5, 7, 8, 8, 5])

In [43]:
s11.dtype

dtype('int64')

In [44]:
s11.max()

9

In [45]:
s11.min()

5

In [46]:
s11[::-1]

array([5, 8, 8, 7, 5, 7, 5, 7, 8, 8, 5, 5, 6, 8, 8, 8, 5, 7, 9, 5])

In [51]:
s11

array([5, 9, 7, 5, 8, 8, 8, 6, 5, 5, 8, 8, 7, 5, 7, 5, 7, 8, 8, 5])

In [52]:
s11.argmax()

1

In [53]:
s11.argmin()

0

In [54]:
s11.mean()

6.7

In [55]:
# Slicing 
a = np.random.randint(5,12, size=(4,5))
a

array([[11, 10,  9,  7, 10],
       [ 6,  7,  5,  6, 10],
       [ 8,  8,  8,  8, 11],
       [ 6,  9,  9, 11,  8]])

In [58]:
a[:2, 0:3] # satır 0dan 2ye sütun 0dan 3e

array([[11, 10,  9],
       [ 6,  7,  5]])

In [59]:
x = np.array([[1,2], [3,4]], dtype=np.float64)
y = np.array([[1,2], [3,4]], dtype=np.float64)

print(x + y)
print(np.add(x,y))

[[2. 4.]
 [6. 8.]]
[[2. 4.]
 [6. 8.]]


In [61]:
x = np.array([[1,2], [3,4]], dtype=np.float64)
y = np.array([[1,2], [3,4]], dtype=np.float64)

print(x - y)
print(np.subtract(x,y))

[[0. 0.]
 [0. 0.]]
[[0. 0.]
 [0. 0.]]


dot product matrix, iç çarpım

In [62]:
print(np.dot(x,y))

[[ 7. 10.]
 [15. 22.]]


In [65]:
# transpose
s8 = np.random.randint(1,10, size=(5,3))
s8

array([[5, 3, 8],
       [8, 2, 8],
       [9, 7, 5],
       [3, 7, 6],
       [3, 8, 5]])

In [66]:
s8.T

array([[5, 8, 9, 3, 3],
       [3, 2, 7, 7, 8],
       [8, 8, 5, 6, 5]])

In [68]:
s8.T.shape

(3, 5)

# Pandas



In [69]:
import pandas as pd

In [72]:
a = pd.Series([10, 55, 12, 4, 5])
a

0    10
1    55
2    12
3     4
4     5
dtype: int64

seriler tek boyutludur

In [73]:
a.axes

[RangeIndex(start=0, stop=5, step=1)]

0dan başlar 5 e kadar 


In [74]:
a

0    10
1    55
2    12
3     4
4     5
dtype: int64

In [75]:
a.size

5

In [76]:
a.dtype

dtype('int64')

In [77]:
a.ndim

1

In [78]:
a.values

array([10, 55, 12,  4,  5])

In [79]:
a.index

RangeIndex(start=0, stop=5, step=1)

In [80]:
a.head(2)

0    10
1    55
dtype: int64

In [81]:
a.tail(2)

3    4
4    5
dtype: int64

In [83]:
b = pd.Series([99, 23, 34, 44, 2323, 12], index=[1,3,5,7,12,23])

In [84]:
b

1       99
3       23
5       34
7       44
12    2323
23      12
dtype: int64

In [85]:
b = pd.Series([99, 23, 34, 44, 2323, 12], index=["a","b","c","d","e","f"])
b

a      99
b      23
c      34
d      44
e    2323
f      12
dtype: int64

In [86]:
b["a":"c"]

a    99
b    23
c    34
dtype: int64

In [87]:
b["b"]

23

In [88]:
liste = [1,2,3,4,5,6]
df = pd.DataFrame(liste, columns=["degiskenler"])
df

degiskenler
0            1
1            2
2            3
3            4
4            5
5            6

In [89]:
import numpy as np
m = np.arange(1,10).reshape((3,3))
df = pd.DataFrame(m, columns=["var1", "var2", "var3"])

In [90]:
df.columns

Index(['var1', 'var2', 'var3'], dtype='object')

In [91]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [92]:
df.describe()

var1  var2  var3
count   3.0   3.0   3.0
mean    4.0   5.0   6.0
std     3.0   3.0   3.0
min     1.0   2.0   3.0
25%     2.5   3.5   4.5
50%     4.0   5.0   6.0
75%     5.5   6.5   7.5
max     7.0   8.0   9.0

In [93]:
df.describe().T

count  mean  std  min  25%  50%  75%  max
var1    3.0   4.0  3.0  1.0  2.5  4.0  5.5  7.0
var2    3.0   5.0  3.0  2.0  3.5  5.0  6.5  8.0
var3    3.0   6.0  3.0  3.0  4.5  6.0  7.5  9.0

In [94]:
df.drop("var1", axis = 1) #sildik ama kalıcı değil

var2  var3
0     2     3
1     5     6
2     8     9

In [96]:
df

var1  var2  var3
0     1     2     3
1     4     5     6
2     7     8     9

In [95]:
"var1" in df

True

In [97]:
df.drop("var1", axis = 1, inplace=True) #sildik kalıcı 

In [98]:
df

var2  var3
0     2     3
1     5     6
2     8     9

In [99]:
"var1" in df

False

In [100]:
"var2" in df

True

In [102]:
import numpy as np
import pandas as pd
m = np.random.randint(1,30, size = (10,3))
df = pd.DataFrame(m, columns=["var1", "var2", "var3"])
df

var1  var2  var3
0    12    15    22
1    10    15     9
2     1    14     6
3    15     1    15
4    14    12    25
5    29     5    12
6     3    11    14
7    16    13    15
8    29    18    27
9    28    18    13

In [103]:
print(df.loc[0:3])  # label base
print(df.iloc[0:3]) # index base

   var1  var2  var3
0    12    15    22
1    10    15     9
2     1    14     6
3    15     1    15
   var1  var2  var3
0    12    15    22
1    10    15     9
2     1    14     6


In [104]:
import numpy as np
import pandas as pd
m = np.random.randint(1,30, size = (10,3))
df1 = pd.DataFrame(m, columns=["var1", "var2", "var3"])
df1 

var1  var2  var3
0    19    14     5
1    25    25    17
2    23    22    13
3     9    18    18
4    11    27     8
5    20    16    18
6     3    22    16
7     8     8     4
8    20    27    29
9    25    22    15

In [105]:
df2 = df1 + 99
df2

var1  var2  var3
0   118   113   104
1   124   124   116
2   122   121   112
3   108   117   117
4   110   126   107
5   119   115   117
6   102   121   115
7   107   107   103
8   119   126   128
9   124   121   114

In [110]:
pd.concat([df1, df2], ignore_index=True, join="inner")

var1  var2  var3
0     19    14     5
1     25    25    17
2     23    22    13
3      9    18    18
4     11    27     8
5     20    16    18
6      3    22    16
7      8     8     4
8     20    27    29
9     25    22    15
10   118   113   104
11   124   124   116
12   122   121   112
13   108   117   117
14   110   126   107
15   119   115   117
16   102   121   115
17   107   107   103
18   119   126   128
19   124   121   114